---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-secret
  namespace: default
spec:
  encryptedData:
    password: AgBYlyArdA1vx/vbOZp1G/XcZwgYBTgqAVsLINziDQMXX2lhodehmxDagNl+v4Tu509DV05fTGtHdL/q5DopcQy1KLIZMfLl8i14Y9eU1tdThvPCNGK2P5s2uUZVUFaZAwGGZbeDbZaLRso7c+1WDDyo3HNaiQNpNqSGxWwUddIOFAMmZdSQUdg/TL7qqGYfQuXjcRvURSLJsouLI/NjcZ08yq/WUoNOHzj3aP+QMUZxjas0hHDnZ8TCOkrKeevwwCkn2ZU7JUy3lH2/Z0tWr7NpNnFsRbUIE3wnZRWTvVOGHnOiWK4OSQLWO4WH1Al810tlki9WUp7jMQu2alXBTJHoA3xw2hrK/cjLsI9Wv7kVkmJGF7f1JDhajLD1ifSiOG+/8Q79CnQDcz1cOFqNfD2ZlBNgJBuDYEYBWwR08tcmrTtuRU0hTeI89la2sQp4vlTU1HDm5o74D7DqFndDoJKSqgPpYK6v81nhQV+XN/vPqjHJWJiQNPIQX4iNH0ZcvXF591hjEcqtUO8EeTodSddWfFtSBN7nqztvQJ1x5yRXsRsekgURmzcDrzdFODhlS5D1+3MY72tqRcqwbBLSi84U0vCaNe0IooYgTTC6drdDojxxkVJCjzXRj8/6hDU3d22XLD2s28xqbkerbmNykJYUFh3eOoN5/01hP76i+tBwFUl3KyZmjTziC+JVFG1G6zB/O9I1CJhcwab5TQ==
  template:
    metadata:
      creationTimestamp: null
      name: db-secret
      namespace: default
    type: Opaque
